input_shape :  [50, 37, 3]
encodings_len: 128
margin: 0.4
mode : 'siamese'
distance_type : 'l2'
backbone : 'nasnetmobile'
backbone_weights : None
freeze_backbone : False
#augmentation_type : None
min_n_obj_per_class : 0 
select_max_n_obj_per_class : 30
max_n_obj_per_class : 50
embeddings_normalization: True
to_validate : False
verbose: True

# optimizer parameters
optimizer : 'radam'
learning_rate : 0.0001
decay_factor : 0.99999
step_size : 1

# embeddings learning training parameters
n_epochs : 1000
n_steps_per_epoch : 200
val_batch_size : 16
val_steps : 10
negatives_selection_mode : 'semihard'
mining_n_classes: 2
mining_n_samples: 7
es_patience : 25

# softmax pretraining parameters
softmax_pretraining : True
softmax_batch_size_train : 32
softmax_batch_size_val : 16
softmax_val_steps : 500
softmax_steps_per_epoch : 100
softmax_epochs : 100
softmax_is_binary: False

# paths
work_dir : 'work_dirs/nu_cvpr2016_mdipfl50_nasnet_siamese/'
dataset_path : 'Dataset/CVPR2016_MDIPFL50/'
plot_history : True
model_save_name : 'best_model_nu_cvpr2016_mdipfl50_nasnet_siamese.h5'
encodings_save_name: 'encodings_nu_cvpr2016_mdipfl50_nasnet_siamese.pkl'

# encodings parameters
save_encodings : True
centers_only: False
max_num_samples_of_each_class : 30
knn_k : 1